const SIGNS=[
{k:'belier',n:'Bélier',g:'♈︎',msg:'Une impulsion juste peut ouvrir une porte aujourd’hui.',sub:'Avancez avec courage, sans précipitation.',aff:'Lion',affG:'♌︎',affSub:'Belle alliance de feu, élan et confiance.',stone:'Grenat',color:'Rouge or',num:'3',love:83,money:66,mood:79,energy:88,conseil:'Choisissez une action simple et terminez-la avant d’en commencer une autre.'},
{k:'taureau',n:'Taureau',g:'♉︎',msg:'La stabilité vous donne une vraie force aujourd’hui.',sub:'Restez ancré, la clarté vient dans le calme.',aff:'Vierge',affG:'♍︎',affSub:'Connexion stable, fiable et rassurante.',stone:'Quartz rose',color:'Vert doré',num:'6',love:88,money:79,mood:76,energy:71,conseil:'Avancez sans vous presser. Une décision posée vaut mieux qu’un grand mouvement forcé.'},
{k:'gemeaux',n:'Gémeaux',g:'♊︎',msg:'Une conversation peut débloquer une situation.',sub:'Léger et vif, votre esprit ouvre des passages.',aff:'Balance',affG:'♎︎',affSub:'Fluidité, échanges et bonne complicité.',stone:'Citrine',color:'Jaune clair',num:'5',love:73,money:74,mood:86,energy:80,conseil:'Dites ce que vous ressentez simplement. La clarté évite les détours inutiles.'},
{k:'cancer',n:'Cancer',g:'♋︎',msg:'Votre intuition capte ce que les mots ne disent pas.',sub:'Fiez-vous à votre ressenti profond.',aff:'Poissons',affG:'♓︎',affSub:'Une douceur sincère et protectrice.',stone:'Pierre de lune',color:'Perle',num:'2',love:90,money:68,mood:84,energy:72,conseil:'Protégez votre énergie. Gardez de la place pour ce qui vous apaise vraiment.'},
{k:'lion',n:'Lion',g:'♌︎',msg:'L’univers vous invite à ralentir pour entendre votre voix intérieure.',sub:'Faites confiance à votre intuition, elle connaît le chemin.',aff:'Taureau',affG:'♉︎',affSub:'Connexion solide et bienveillante.',stone:'Citrine',color:'Or solaire',num:'7',love:87,money:72,mood:90,energy:85,conseil:'Aujourd’hui, choisissez une seule action importante. Faites-la lentement, avec présence.'},
{k:'vierge',n:'Vierge',g:'♍︎',msg:'Un détail bien réglé peut alléger toute votre journée.',sub:'L’ordre juste vous redonne de l’espace.',aff:'Capricorne',affG:'♑︎',affSub:'Énergie constructive et très fiable.',stone:'Jaspe',color:'Sable doré',num:'4',love:77,money:81,mood:74,energy:78,conseil:'Simplifiez votre liste. Une priorité claire suffit pour reprendre la main.'},
{k:'balance',n:'Balance',g:'♎︎',msg:'L’harmonie revient quand vous arrêtez de porter tout seul.',sub:'Un choix équilibré vous fera du bien.',aff:'Gémeaux',affG:'♊︎',affSub:'Compréhension, légèreté et lien naturel.',stone:'Lapis',color:'Rose doré',num:'8',love:84,money:69,mood:82,energy:73,conseil:'Cherchez l’équilibre, mais ne vous oubliez pas pour garder la paix.'},
{k:'scorpion',n:'Scorpion',g:'♏︎',msg:'Une vérité intérieure demande à être respectée.',sub:'Restez lucide, votre force est précise.',aff:'Cancer',affG:'♋︎',affSub:'Profondeur émotionnelle et loyauté.',stone:'Obsidienne',color:'Pourpre',num:'9',love:75,money:77,mood:80,energy:84,conseil:'Ne forcez pas les réponses. Observez, puis agissez avec précision.'},
{k:'sagittaire',n:'Sagittaire',g:'♐︎',msg:'Un nouvel horizon vous redonne de l’élan.',sub:'Osez viser plus loin, mais sans vous disperser.',aff:'Bélier',affG:'♈︎',affSub:'Dynamique, stimulante et directe.',stone:'Turquoise',color:'Bleu nuit',num:'1',love:78,money:70,mood:88,energy:91,conseil:'Ouvrez une piste. Même petite, elle peut relancer votre mouvement.'},
{k:'capricorne',n:'Capricorne',g:'♑︎',msg:'Votre patience prépare une avancée solide.',sub:'La constance vous rend puissant aujourd’hui.',aff:'Taureau',affG:'♉︎',affSub:'Lente, sûre et efficace.',stone:'Onyx',color:'Bronze',num:'10',love:74,money:85,mood:72,energy:79,conseil:'Gardez le cap. Une étape régulière vaut mieux qu’un effort épuisant.'},
{k:'verseau',n:'Verseau',g:'♒︎',msg:'Une idée différente peut devenir votre avantage.',sub:'L’inspiration revient dès que vous respirez mieux.',aff:'Sagittaire',affG:'♐︎',affSub:'Ouverture, liberté et vision commune.',stone:'Améthyste',color:'Électrique',num:'11',love:71,money:73,mood:87,energy:82,conseil:'Notez l’idée qui revient souvent. Elle peut contenir votre prochaine direction.'},
{k:'poissons',n:'Poissons',g:'♓︎',msg:'Votre sensibilité devient une boussole précieuse.',sub:'Le calme vous aide à entendre la bonne réponse.',aff:'Cancer',affG:'♋︎',affSub:'Lien intuitif, tendre et protecteur.',stone:'Aigue-marine',color:'Bleu doré',num:'7',love:90,money:70,mood:82,energy:74,conseil:'Accordez-vous un vrai moment de silence. Votre intuition sait déjà ce qui compte.'}
];
const $=s=>document.querySelector(s);const wheel=$('#wheel');let current=Number(localStorage.getItem('astro-v23-2-index')||11);let rotation=0,startX=0,startRot=0,dragging=false;
function a(){return SIGNS[current]}function dateFR(){return new Date().toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}function haptic(){try{navigator.vibrate?.(14)}catch(e){}}
function renderWheel(){[...wheel.querySelectorAll('.sign')].forEach(e=>e.remove());SIGNS.forEach((s,i)=>{let el=document.createElement('button');el.className='sign'+(i===current?' active':'');el.innerHTML=`<b>${s.g}</b><span>${s.n}</span>`;el.onclick=e=>{e.stopPropagation();select(i)};wheel.appendChild(el)});positionSigns()}
function positionSigns(){let rad=Math.min(wheel.clientWidth,wheel.clientHeight)*0.372;[...wheel.querySelectorAll('.sign')].forEach((el,i)=>{let ang=i*30+rotation;el.style.transform=`rotate(${ang}deg) translateY(-${rad}px) rotate(${-ang}deg)`})}
function render(){let s=a();localStorage.setItem('astro-v23-2-index',current);$('#profileBtn').textContent=s.g;$('#dateLine').textContent=dateFR();$('#mainMessage').textContent=s.msg;$('#subMessage').textContent=s.sub;$('#loveVal').textContent=s.love+'%';$('#moneyVal').textContent=s.money+'%';$('#moodVal').textContent=s.mood+'%';$('#energyVal').textContent=s.energy+'%';$('#affGlyph').textContent=s.affG;$('#affTitle').textContent='Affinité du jour : '+s.aff;$('#affSub').textContent=s.affSub;$('#numVal').textContent=s.num;$('#colorVal').textContent=s.color;$('#stoneVal').textContent=s.stone;rotation=-current*30;renderWheel();renderPicker()}
function select(i){current=i;haptic();render()}function next(){select((current+1)%12)}function prev(){select((current+11)%12)}function idxFromRot(){let n=((rotation%360)+360)%360;return Math.round((360-n)/30)%12}
function renderPicker(){$('#signGrid').innerHTML=SIGNS.map((s,i)=>`<button class="zbtn ${i===current?'sel':''}" data-i="${i}"><span class="g">${s.g}</span><span class="n">${s.n}</span></button>`).join('');document.querySelectorAll('.zbtn').forEach(b=>b.onclick=()=>{select(Number(b.dataset.i));closePicker()})}
function openPicker(){$('#picker').classList.add('open')}function closePicker(){$('#picker').classList.remove('open')}function modal(html){$('#modal').innerHTML=html;$('#modalLayer').classList.add('open')}function closeModal(){$('#modalLayer').classList.remove('open')}
function conseil(){let s=a();modal(`<small>Conseil complet</small><h2>${s.g} ${s.n}</h2><p>${s.conseil}</p><div class="note">Amour ${s.love}% · Argent ${s.money}% · Humeur ${s.mood}% · Énergie ${s.energy}%</div><div class="note">Nombre ${s.num} · Couleur ${s.color} · Pierre ${s.stone}</div><button class="btn" onclick="closeModal()">Compris</button>`)}
function aff(){let s=a();modal(`<small>Affinité du jour</small><h2>${s.affG} ${s.aff}</h2><p>${s.affSub}</p><button class="btn" onclick="closeModal()">Fermer</button>`)}
function detail(k){let s=a();let v={Amour:s.love,Argent:s.money,Humeur:s.mood,'Énergie':s.energy}[k];modal(`<small>${k}</small><h2>${v}%</h2><p>Votre vibration ${k.toLowerCase()} du jour pour ${s.n}.</p><button class="btn" onclick="closeModal()">Fermer</button>`)}
function luck(k){let s=a();let v={Nombre:s.num,Couleur:s.color,Pierre:s.stone}[k];modal(`<small>${k}</small><h2>${v}</h2><p>Votre élément chanceux du jour pour ${s.n}.</p><button class="btn" onclick="closeModal()">Fermer</button>`)}
function menu(){let s=a();modal(`<small>Astro Galactic</small><h2>Menu</h2><p>Signe actif : ${s.g} ${s.n}</p><button class="btn" onclick="closeModal();openPicker()">Choisir un signe</button><button class="btn btn2" onclick="closeModal()">Fermer</button>`)}
function profile(){let s=a();modal(`<small>Profil astral</small><h2>${s.g} ${s.n}</h2><p>${s.sub}</p><button class="btn" onclick="closeModal();openPicker()">Changer mon signe</button><button class="btn btn2" onclick="closeModal()">Fermer</button>`)}
$('#menuBtn').onclick=menu;$('#profileBtn').onclick=profile;$('#prevBtn').onclick=prev;$('#nextBtn').onclick=next;$('#conseilBtn').onclick=conseil;$('#affinityBtn').onclick=aff;$('#closePicker').onclick=closePicker;$('#modalLayer').onclick=e=>{if(e.target.id==='modalLayer')closeModal()};document.querySelectorAll('.stat').forEach(b=>b.onclick=()=>detail(b.dataset.stat));document.querySelectorAll('.luck').forEach(b=>b.onclick=()=>luck(b.dataset.luck));
wheel.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;startRot=rotation;wheel.setPointerCapture(e.pointerId)});wheel.addEventListener('pointermove',e=>{if(!dragging)return;rotation=startRot+(e.clientX-startX)*.42;positionSigns()});wheel.addEventListener('pointerup',()=>{if(!dragging)return;dragging=false;select(idxFromRot())});window.addEventListener('resize',positionSigns);render();if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{})}
